spring.datasource.url : jdbc:postgresql://127.0.0.1/postgres
spring.datasource.username : postgres
spring.datasource.password : test123

#spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.MySQL5InnoDBDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation : true
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto : update

# Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: info
    org.hibernate: info

# Server configuration
server:
  port: 8080

# security related
security:
  salt: willislin